### PR TITLE
Copy gym_evaluator.py into labs/03

### PR DESCRIPTION
**Pull request by filipbartek**
Copy from labs/02. gym_evaluator.py is imported in:

* labs/03/mountain_car_evaluator.py
* labs/03/lunar_lander_evaluator.py

The version from labs/02 seems compatible with labs/03.

### CODE REVIEW

**Comment by foxik** [comment]
I am deliberately using only one version of `gym_evaluator` (for example, the task description links the `gym_evaluator` from labs/02) -- so I am not eager to merge the pull request yet. It seemed to me that having only one file would be cleaner, but maybe it is too burdensome for the students? Ideally I would use a symlink, but that does not play nicely on Windows, I assume; we can modify the templates to also include the content of directory "../02"; personally I am using PYTHONPATH to automatically include the module from a different directory.

I was worried that having multiple "same" files can lead to a problem of them diverging, but if I am careful and make sure all "gym_evaluator"s are always the same, maybe it would be fine.

Do you have any thoughts on that?

**Comment by filipbartek** [comment]
I understand. I agree that keeping two copies of `gym_evaluator.py` is a potential pain. I don't know any canonical solution to this issue.

I think that any of the following changes would improve on the current situation:

- Keep all the labs sources in one directory (for example `labs`).
- Introduce a new directory (for example `labs/common`) for common functionality. Require the users to ensure that this directory is in `PYTHONPATH`.
- Rename the lab directories so that they are valid package names (for example `lab02` instead of `02`). Require the users to ensure that `labs` is in `PYTHONPATH`. Use cross-package imports such as `import lab02.gym_evaluator`.

All of these changes may be better introduced after this semester to preserve compatibility with the existing solutions during this semester.

**Comment by foxik** [comment]
Thanks for spending time writing the mail.
- I believe having just one directory is too impractical -- at least I usually end up with ten or even more files for each lab, so having ~100 files in a directory would be bad (and the lab-in-a-dir approach allows me to find the required files fast)
- both other approaches require something in PYTHONPATH. But the last approach you mention seems quite nice (the distinction between common and non-common may be difficult, while saying "I want a module from lab X" seems fine).

But for this semester -- it seems the best solution is to duplicate all files and have each lab directory completely independent on the other ones (i.e., your original pull request)?

**Comment by filipbartek** [comment]
> But for this semester -- it seems the best solution is to duplicate all files and have each lab directory completely independent on the other ones (i.e., your original pull request)?

Sounds ok to me.

**Comment by foxik** [comment]
Merging.

**Pull request merged**
